language: java
jdk: openjdk11

# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

matrix:
	include:
	- env:FILE=labone
	- ens:FILE=labtwo

env: 
  - PRO_SPECIAL_BUILD='early-access'

install:
  - cd $FILE
  - java pro_wrapper.java version


script:
  - ./pro/bin/pro version
  - ./pro/bin/pro
